app = "${APP_NAME}"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[mounts]
  source = "headscale"
  destination = "/var/lib/headscale"

[metrics]
    port = 9091
    path = "/metrics"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.http_checks]]
    grace_period = "6s"
    interval = 10000
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = 2000
    tls_skip_verify = true
    [services.http_checks.headers]

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[services]]
  internal_port = 50443
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls"]
    port = "50443"
    [services.ports.tls_options]
      alpn = ["h2"]
